name: Test Model

on:
  push:
    branches: sam_mla
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pytest modal

      - name: Setup Modal
        run: modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Run tests on Modal GPU
        run: modal run tests/test_model_initialization.py::modal_main

      - name: Train model
        run: modal run training/modal_train.py::main
